from __future__ import annotations

import argparse
from contextlib import contextmanager
import fcntl
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

from rsps_crewai_team.runtime.settings import LOGS_DIR, PROJECT_ROOT, bool_env
from rsps_crewai_team.runtime.agency import load_agency_workflows
from rsps_crewai_team.runtime.orchestrator import create_workflow_run, list_workflow_runs
from rsps_crewai_team.runtime.work_orders import ensure_work_order_dirs
from rsps_crewai_team.worker import run_duo, run_once


CRON_TEMPLATE = """# RSPS CrewAI autonomous development scheduler
# Generated by: uv run rsps-cron render
SHELL=/bin/bash
PATH=/var/home/Scaar/.local/bin:/usr/local/bin:/usr/bin:/bin

# Runs the OpenClaw coding duo every minute. It will only modify the RSPS
# repo when RSPS_ALLOW_AUTONOMOUS=true is set in /var/home/Scaar/Desktop/game project/Daedalus/.env.
* * * * * cd '/var/home/Scaar/Desktop/game project/Daedalus' && /var/home/Scaar/.local/bin/uv run rsps-cron tick >> '/var/home/Scaar/Desktop/game project/Daedalus/logs/cron.log' 2>&1

# Daily planning packet refresh. This is read-only unless the worker is invoked separately.
15 3 * * * cd '/var/home/Scaar/Desktop/game project/Daedalus' && /var/home/Scaar/.local/bin/uv run rsps-team "Review current RSPS development status and propose the next 3 work orders." >> '/var/home/Scaar/Desktop/game project/Daedalus/logs/daily-planning.log' 2>&1
"""

SYSTEMD_SERVICE_TEMPLATE = """[Unit]
Description=Daedalus autonomous development tick

[Service]
Type=oneshot
WorkingDirectory=/var/home/Scaar/Desktop/game project/Daedalus
Environment=PYTHONDONTWRITEBYTECODE=1
ExecStart=/var/home/Scaar/.local/bin/uv run rsps-cron tick
StandardOutput=append:/var/home/Scaar/Desktop/game project/Daedalus/logs/cron.log
StandardError=append:/var/home/Scaar/Desktop/game project/Daedalus/logs/cron.log
"""

SYSTEMD_TIMER_TEMPLATE = """[Unit]
Description=Run Daedalus autonomous development watchdog every minute

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min
AccuracySec=15s
Persistent=true

[Install]
WantedBy=timers.target
"""


def tick(_: argparse.Namespace) -> None:
    load_dotenv(PROJECT_ROOT / ".env")
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    with tick_lock() as acquired:
        if not acquired:
            print(f"[{datetime.now(timezone.utc).isoformat()}] rsps-cron tick skipped: previous tick still running")
            return
        print(f"[{datetime.now(timezone.utc).isoformat()}] rsps-cron watchdog tick")
        runs = list_workflow_runs(limit=3)
        print(f"workflow_runs={len(runs)}")
        ensure_self_fulfilling_backlog()
        if not bool_env("RSPS_ALLOW_AUTONOMOUS", False):
            print("Autonomous execution disabled. Set RSPS_ALLOW_AUTONOMOUS=true to run workers.")
            return
        if is_rsps_work_active():
            print("RSPS work is already active. Watchdog will not start another worker.")
            return
        if bool_env("RSPS_DUO_MODE", True):
            run_duo(argparse.Namespace())
        else:
            run_once(argparse.Namespace())


@contextmanager
def tick_lock():
    path = LOGS_DIR / "rsps-cron.tick.lock"
    handle = path.open("w", encoding="utf-8")
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        handle.close()
        yield False
        return
    try:
        handle.write(datetime.now(timezone.utc).isoformat())
        handle.flush()
        yield True
    finally:
        fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        handle.close()


def is_rsps_work_active() -> bool:
    ensure_work_order_dirs()
    return any((PROJECT_ROOT / "work_orders" / "running").glob("*.md"))


def ensure_self_fulfilling_backlog() -> None:
    workflow_id = autonomy_workflow_id()
    ensure_work_order_dirs()
    queued = list((PROJECT_ROOT / "work_orders" / "inbox").glob("*.md"))
    running = list((PROJECT_ROOT / "work_orders" / "running").glob("*.md"))
    if queued or running:
        return
    created = create_workflow_run(workflow_id, title="Self-filling autonomous studio cycle")
    print(f"created_workflow_run={created['run_id']}")


def autonomy_workflow_id() -> str:
    fallback = "server_building_watchdog"
    configured = os.getenv("RSPS_AUTONOMY_WORKFLOW_ID", fallback).strip() or fallback
    known = {str(item.get("id")) for item in load_agency_workflows().get("workflows", [])}
    if configured in known:
        return configured
    print(f"Unknown RSPS_AUTONOMY_WORKFLOW_ID={configured}; using {fallback}.")
    return fallback


def render(_: argparse.Namespace) -> None:
    path = PROJECT_ROOT / "cron" / "rsps-crewai.cron"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CRON_TEMPLATE, encoding="utf-8")
    print(path)


def install(_: argparse.Namespace) -> None:
    render(argparse.Namespace())
    path = PROJECT_ROOT / "cron" / "rsps-crewai.cron"
    if shutil.which("crontab"):
        subprocess.run(["crontab", str(path)], check=True)
        print("Installed user crontab from " + str(path))
        return
    install_systemd_timer()


def install_systemd_timer() -> None:
    user_systemd = Path.home() / ".config" / "systemd" / "user"
    user_systemd.mkdir(parents=True, exist_ok=True)
    service_path = user_systemd / "daedalus-rsps-cron.service"
    timer_path = user_systemd / "daedalus-rsps-cron.timer"
    service_path.write_text(SYSTEMD_SERVICE_TEMPLATE, encoding="utf-8")
    timer_path.write_text(SYSTEMD_TIMER_TEMPLATE, encoding="utf-8")
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", "--now", "daedalus-rsps-cron.timer"], check=True)
    print("crontab was not found; installed user systemd timer " + str(timer_path))


def main() -> None:
    parser = argparse.ArgumentParser(description="RSPS autonomous development cron helper.")
    subparsers = parser.add_subparsers(required=True)
    tick_parser = subparsers.add_parser("tick", help="Run one scheduled cycle.")
    tick_parser.set_defaults(func=tick)
    render_parser = subparsers.add_parser("render", help="Write cron file without installing it.")
    render_parser.set_defaults(func=render)
    install_parser = subparsers.add_parser("install", help="Install the generated cron file with crontab.")
    install_parser.set_defaults(func=install)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
